-- Batkart – Supabase schema for turlagring (per bruker, båt klar for senere)
-- Kjør i Supabase SQL Editor. Trygt å kjøre flere ganger (idempotent).

-- ── Tabell ────────────────────────────────────────────────────────────────────
create table if not exists public.trips (
  id            text primary key default gen_random_uuid()::text,  -- delt id lokalt/sky
  user_id       uuid not null references auth.users (id) on delete cascade,
  boat_id       uuid,                       -- null nå; brukes når båt-velger kommer
  name          text not null,
  trip_date     timestamptz not null default now(),
  distance_m    double precision not null default 0,
  duration_s    integer not null default 0,
  avg_speed_ms  double precision not null default 0,
  max_speed_ms  double precision not null default 0,
  started_at    timestamptz,                -- nøyaktig start (første GPS-punkt)
  ended_at      timestamptz,                -- nøyaktig stopp (siste GPS-punkt)
  icon          text,
  points        jsonb not null default '[]'::jsonb,   -- [{lat,lng}, ...]
  created_at    timestamptz not null default now()
);

create index if not exists trips_user_id_idx on public.trips (user_id);
create index if not exists trips_user_date_idx on public.trips (user_id, trip_date desc);

-- ── Tilgang: gi innlogget rolle rett til tabellen (RLS styrer hvilke rader) ─────
grant select, insert, update, delete on public.trips to authenticated;

-- ── Row Level Security: hver bruker ser/endrer kun egne turer ──────────────────
alter table public.trips enable row level security;

drop policy if exists "trips_select_own" on public.trips;
create policy "trips_select_own" on public.trips
  for select using (auth.uid() = user_id);

drop policy if exists "trips_insert_own" on public.trips;
create policy "trips_insert_own" on public.trips
  for insert with check (auth.uid() = user_id);

drop policy if exists "trips_update_own" on public.trips;
create policy "trips_update_own" on public.trips
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "trips_delete_own" on public.trips;
create policy "trips_delete_own" on public.trips
  for delete using (auth.uid() = user_id);

-- ── Kundeprofil: app-data + preferanser (1:1 med auth.users) ───────────────────
create table if not exists public.profiles (
  id               uuid primary key references auth.users (id) on delete cascade,
  display_name     text,
  report_frequency text not null default 'none',   -- 'none' | 'weekly' | 'monthly'
  report_email     text,                            -- valgfri; ellers auth-epost
  marketing_opt_in boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
alter table public.profiles enable row level security;
grant select, insert, update on public.profiles to authenticated;
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- Auto-opprett profil når en ny bruker registreres
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id) on conflict do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill profiler for eksisterende brukere
insert into public.profiles (id) select id from auth.users on conflict do nothing;

-- ── Samtykke-/preferanse-historikk (append-only, GDPR-bevis) ───────────────────
-- profiles holder NÅ-verdien; denne holder DATERT historikk (ja OG nei).
create table if not exists public.consent_log (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  kind       text not null,                 -- f.eks. 'marketing' | 'report_frequency'
  value      text not null,                 -- 'true'/'false' eller 'monthly' osv.
  changed_at timestamptz not null default now()
);
create index if not exists consent_log_user_idx on public.consent_log (user_id, kind, changed_at desc);
alter table public.consent_log enable row level security;
grant select, insert on public.consent_log to authenticated;
drop policy if exists "consent_select_own" on public.consent_log;
create policy "consent_select_own" on public.consent_log
  for select using (auth.uid() = user_id);
drop policy if exists "consent_insert_own" on public.consent_log;
create policy "consent_insert_own" on public.consent_log
  for insert with check (auth.uid() = user_id);

-- ── Samtykke-logg: hver brukers aksept av bruksvilkår (bevis) ───────────────────
create table if not exists public.tos_acceptances (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  version     text not null,
  terms_hash  text,                         -- SHA-256 av teksten brukeren godtok
  accepted_at timestamptz not null,
  created_at  timestamptz not null default now(),
  unique (user_id, version)
);
alter table public.tos_acceptances enable row level security;
grant select, insert on public.tos_acceptances to authenticated;
drop policy if exists "tos_select_own" on public.tos_acceptances;
create policy "tos_select_own" on public.tos_acceptances
  for select using (auth.uid() = user_id);
drop policy if exists "tos_insert_own" on public.tos_acceptances;
create policy "tos_insert_own" on public.tos_acceptances
  for insert with check (auth.uid() = user_id);

-- ── Analytics (anonym, session-basert) ─────────────────────────────────────────
create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  session_id  text,
  event       text not null,
  payload     jsonb,
  created_at  timestamptz not null default now()
);

-- Tillat anonym innsetting (klient-analytics), men ingen lesing via anon/authenticated.
alter table public.events enable row level security;
grant insert on public.events to anon, authenticated;
drop policy if exists "events_insert_any" on public.events;
create policy "events_insert_any" on public.events
  for insert with check (true);

-- ── Betaling / abonnement / tilgang (Stripe-speil) ─────────────────────────────
-- Stripe eier betaling/fornying/refusjon. Vi speiler status og avleder tilgang.
-- Skriving skjer KUN server-side (webhook med service_role). Brukere kun leser egne.

alter table public.profiles add column if not exists stripe_customer_id text;

-- Produktkatalog (data, ikke hardkodet i app)
create table if not exists public.product (
  id          text primary key,             -- f.eks. 'premium'
  name        text not null,
  description text,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Prisplaner (ett produkt kan ha flere: mnd/år/kampanje)
create table if not exists public.price_plan (
  id              text primary key,          -- kan = stripe_price_id
  product_id      text not null references public.product (id),
  stripe_price_id text unique,
  interval        text,                       -- 'month' | 'year' | 'one_time'
  amount_cents    integer,
  currency        text not null default 'nok',
  trial_days      integer not null default 0,
  active          boolean not null default true,
  created_at      timestamptz not null default now()
);

-- Abonnement = speil av Stripe
create table if not exists public.subscription (
  id                   text primary key,      -- stripe_subscription_id
  user_id              uuid not null references auth.users (id) on delete cascade,
  price_plan_id        text references public.price_plan (id),
  status               text not null,          -- trial|active|past_due|canceled|unpaid|incomplete
  current_period_end   timestamptz,
  cancel_at_period_end boolean not null default false,
  trial_end            timestamptz,
  started_at           timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index if not exists subscription_user_idx on public.subscription (user_id);

-- Entitlement = hva brukeren har tilgang til NÅ (avledet av abonnement, ELLER gitt
-- manuelt til test-/gratisbrukere). `source` skiller dem så Stripe-webhook kun rører
-- sine egne ('stripe') og ikke overskriver comp/beta-tilgang.
create table if not exists public.entitlement (
  id                    bigint generated by default as identity primary key,
  user_id               uuid not null references auth.users (id) on delete cascade,
  feature_key           text not null,         -- f.eks. 'premium'
  active                boolean not null default true,
  source                text not null default 'stripe',  -- 'stripe' | 'comp' | 'beta'
  source_subscription_id text references public.subscription (id) on delete set null,
  valid_until           timestamptz,            -- null = så lenge active=true
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (user_id, feature_key)
);

-- Tilgang: katalog er offentlig lesbar; abonnement/entitlement kun egne (les).
alter table public.product enable row level security;
alter table public.price_plan enable row level security;
alter table public.subscription enable row level security;
alter table public.entitlement enable row level security;
grant select on public.product, public.price_plan to anon, authenticated;
grant select on public.subscription, public.entitlement to authenticated;
drop policy if exists "product_read" on public.product;
create policy "product_read" on public.product for select using (true);
drop policy if exists "price_read" on public.price_plan;
create policy "price_read" on public.price_plan for select using (true);
drop policy if exists "sub_select_own" on public.subscription;
create policy "sub_select_own" on public.subscription for select using (auth.uid() = user_id);
drop policy if exists "ent_select_own" on public.entitlement;
create policy "ent_select_own" on public.entitlement for select using (auth.uid() = user_id);
-- (ingen insert/update-policy for brukere → kun service_role/webhook skriver)

-- Fail-safe tilgangssjekk: aktiv OG ikke utløpt. Appen kaller denne (RPC).
-- Selv om en webhook skulle mangle, gir en utløpt valid_until ingen tilgang.
create or replace function public.has_feature(feature text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.entitlement e
    where e.user_id = auth.uid()
      and e.feature_key = feature
      and e.active = true
      and (e.valid_until is null or e.valid_until > now())
  );
$$;

-- ── Admin: flagg + trygge funksjoner (kalles fra Studio / admin-UI) ────────────
alter table public.profiles add column if not exists is_admin boolean not null default false;

-- Er innlogget bruker admin?
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

-- Gi gratis tilgang (kun admin). valid_until = null → evig; ellers tidsbegrenset.
create or replace function public.admin_grant_access(
  p_email text, p_feature text default 'premium', p_valid_until timestamptz default null
) returns void language plpgsql security definer set search_path = public as $$
declare uid uuid;
begin
  if not public.is_admin() then raise exception 'Ikke autorisert'; end if;
  select id into uid from auth.users where lower(email) = lower(p_email);
  if uid is null then raise exception 'Fant ingen bruker med e-post %', p_email; end if;
  insert into public.entitlement (user_id, feature_key, active, source, valid_until)
  values (uid, p_feature, true, 'comp', p_valid_until)
  on conflict (user_id, feature_key)
  do update set active = true, source = 'comp', valid_until = excluded.valid_until, updated_at = now();
end; $$;

-- Fjern tilgang (kun admin)
create or replace function public.admin_revoke_access(
  p_email text, p_feature text default 'premium'
) returns void language plpgsql security definer set search_path = public as $$
declare uid uuid;
begin
  if not public.is_admin() then raise exception 'Ikke autorisert'; end if;
  select id into uid from auth.users where lower(email) = lower(p_email);
  if uid is null then raise exception 'Fant ingen bruker'; end if;
  update public.entitlement set active = false, updated_at = now()
  where user_id = uid and feature_key = p_feature;
end; $$;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.admin_grant_access(text, text, timestamptz) to authenticated;
grant execute on function public.admin_revoke_access(text, text) to authenticated;
