-- Batkart – Supabase schema for turlagring (per bruker, båt klar for senere)
-- Kjør i Supabase SQL Editor. Trygt å kjøre flere ganger (idempotent).

-- ── Tabell ────────────────────────────────────────────────────────────────────
create table if not exists public.trips (
  id            text primary key default gen_random_uuid()::text,  -- delt id lokalt/sky
  user_id       uuid not null references auth.users (id) on delete cascade,
  boat_id       uuid,                       -- null nå; brukes når båt-velger kommer
  name          text not null,
  trip_date     timestamptz not null default now(),
  distance_m    double precision not null default 0,
  duration_s    integer not null default 0,
  avg_speed_ms  double precision not null default 0,
  max_speed_ms  double precision not null default 0,
  started_at    timestamptz,                -- nøyaktig start (første GPS-punkt)
  ended_at      timestamptz,                -- nøyaktig stopp (siste GPS-punkt)
  icon          text,
  points        jsonb not null default '[]'::jsonb,   -- [{lat,lng}, ...]
  created_at    timestamptz not null default now()
);

create index if not exists trips_user_id_idx on public.trips (user_id);
create index if not exists trips_user_date_idx on public.trips (user_id, trip_date desc);

-- ── Tilgang: gi innlogget rolle rett til tabellen (RLS styrer hvilke rader) ─────
grant select, insert, update, delete on public.trips to authenticated;

-- ── Row Level Security: hver bruker ser/endrer kun egne turer ──────────────────
alter table public.trips enable row level security;

drop policy if exists "trips_select_own" on public.trips;
create policy "trips_select_own" on public.trips
  for select using (auth.uid() = user_id);

drop policy if exists "trips_insert_own" on public.trips;
create policy "trips_insert_own" on public.trips
  for insert with check (auth.uid() = user_id);

drop policy if exists "trips_update_own" on public.trips;
create policy "trips_update_own" on public.trips
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "trips_delete_own" on public.trips;
create policy "trips_delete_own" on public.trips
  for delete using (auth.uid() = user_id);

-- ── Samtykke-logg: hver brukers aksept av bruksvilkår (bevis) ───────────────────
create table if not exists public.tos_acceptances (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  version     text not null,
  accepted_at timestamptz not null,
  created_at  timestamptz not null default now(),
  unique (user_id, version)
);
alter table public.tos_acceptances enable row level security;
grant select, insert on public.tos_acceptances to authenticated;
drop policy if exists "tos_select_own" on public.tos_acceptances;
create policy "tos_select_own" on public.tos_acceptances
  for select using (auth.uid() = user_id);
drop policy if exists "tos_insert_own" on public.tos_acceptances;
create policy "tos_insert_own" on public.tos_acceptances
  for insert with check (auth.uid() = user_id);

-- ── Analytics (anonym, session-basert) ─────────────────────────────────────────
create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  session_id  text,
  event       text not null,
  payload     jsonb,
  created_at  timestamptz not null default now()
);

-- Tillat anonym innsetting (klient-analytics), men ingen lesing via anon/authenticated.
alter table public.events enable row level security;
grant insert on public.events to anon, authenticated;
drop policy if exists "events_insert_any" on public.events;
create policy "events_insert_any" on public.events
  for insert with check (true);
